require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MagueyesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Magueye. As you add validations to Magueye, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MagueyesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all magueyes as @magueyes" do
      magueye = Magueye.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:magueyes)).to eq([magueye])
    end
  end

  describe "GET #show" do
    it "assigns the requested magueye as @magueye" do
      magueye = Magueye.create! valid_attributes
      get :show, {:id => magueye.to_param}, valid_session
      expect(assigns(:magueye)).to eq(magueye)
    end
  end

  describe "GET #new" do
    it "assigns a new magueye as @magueye" do
      get :new, {}, valid_session
      expect(assigns(:magueye)).to be_a_new(Magueye)
    end
  end

  describe "GET #edit" do
    it "assigns the requested magueye as @magueye" do
      magueye = Magueye.create! valid_attributes
      get :edit, {:id => magueye.to_param}, valid_session
      expect(assigns(:magueye)).to eq(magueye)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Magueye" do
        expect {
          post :create, {:magueye => valid_attributes}, valid_session
        }.to change(Magueye, :count).by(1)
      end

      it "assigns a newly created magueye as @magueye" do
        post :create, {:magueye => valid_attributes}, valid_session
        expect(assigns(:magueye)).to be_a(Magueye)
        expect(assigns(:magueye)).to be_persisted
      end

      it "redirects to the created magueye" do
        post :create, {:magueye => valid_attributes}, valid_session
        expect(response).to redirect_to(Magueye.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved magueye as @magueye" do
        post :create, {:magueye => invalid_attributes}, valid_session
        expect(assigns(:magueye)).to be_a_new(Magueye)
      end

      it "re-renders the 'new' template" do
        post :create, {:magueye => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested magueye" do
        magueye = Magueye.create! valid_attributes
        put :update, {:id => magueye.to_param, :magueye => new_attributes}, valid_session
        magueye.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested magueye as @magueye" do
        magueye = Magueye.create! valid_attributes
        put :update, {:id => magueye.to_param, :magueye => valid_attributes}, valid_session
        expect(assigns(:magueye)).to eq(magueye)
      end

      it "redirects to the magueye" do
        magueye = Magueye.create! valid_attributes
        put :update, {:id => magueye.to_param, :magueye => valid_attributes}, valid_session
        expect(response).to redirect_to(magueye)
      end
    end

    context "with invalid params" do
      it "assigns the magueye as @magueye" do
        magueye = Magueye.create! valid_attributes
        put :update, {:id => magueye.to_param, :magueye => invalid_attributes}, valid_session
        expect(assigns(:magueye)).to eq(magueye)
      end

      it "re-renders the 'edit' template" do
        magueye = Magueye.create! valid_attributes
        put :update, {:id => magueye.to_param, :magueye => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested magueye" do
      magueye = Magueye.create! valid_attributes
      expect {
        delete :destroy, {:id => magueye.to_param}, valid_session
      }.to change(Magueye, :count).by(-1)
    end

    it "redirects to the magueyes list" do
      magueye = Magueye.create! valid_attributes
      delete :destroy, {:id => magueye.to_param}, valid_session
      expect(response).to redirect_to(magueyes_url)
    end
  end

end
