require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TipoDestiladosController, :type => :controller do

  let(:valid_attributes) { FactoryGirl.attributes_for(:tipo_destilado) }

  let(:invalid_attributes) {
    { nombre: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoDestiladosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:usuario_logueado) { Usuario.new }

  before(:each) { allow_any_instance_of(ApplicationController).to receive(:usuario_actual).and_return usuario_logueado }

  describe "GET index" do
    it "assigns all tipo_destilados as @tipo_destilados" do
      tipo_destilado = FactoryGirl.create(:tipo_destilado)
      get :index, {}, valid_session
      expect(assigns(:tipo_destilados)).to eq([tipo_destilado])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_destilado as @tipo_destilado" do
      tipo_destilado = FactoryGirl.create(:tipo_destilado)
      get :show, {:id => tipo_destilado.to_param}, valid_session
      expect(assigns(:tipo_destilado)).to eq(tipo_destilado)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_destilado as @tipo_destilado" do
      get :new, {}, valid_session
      expect(assigns(:tipo_destilado)).to be_a_new(TipoDestilado)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_destilado as @tipo_destilado" do
      tipo_destilado = FactoryGirl.create(:tipo_destilado)
      get :edit, {:id => tipo_destilado.to_param}, valid_session
      expect(assigns(:tipo_destilado)).to eq(tipo_destilado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoDestilado" do
        expect {
          post :create, {:tipo_destilado => valid_attributes}, valid_session
        }.to change(TipoDestilado, :count).by(1)
      end

      it "assigns a newly created tipo_destilado as @tipo_destilado" do
        post :create, {:tipo_destilado => valid_attributes}, valid_session
        expect(assigns(:tipo_destilado)).to be_a(TipoDestilado)
        expect(assigns(:tipo_destilado)).to be_persisted
      end

      it "redirects to the created tipo_destilado" do
        post :create, {:tipo_destilado => valid_attributes}, valid_session
        expect(response).to redirect_to(TipoDestilado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_destilado as @tipo_destilado" do
        post :create, {:tipo_destilado => invalid_attributes}, valid_session
        expect(assigns(:tipo_destilado)).to be_a_new(TipoDestilado)
      end

      it "re-renders the 'new' template" do
        post :create, {:tipo_destilado => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { nombre: 'nuevo nombre' }
      }

      it "updates the requested tipo_destilado" do
        tipo_destilado = FactoryGirl.create(:tipo_destilado)
        put :update, {:id => tipo_destilado.to_param, :tipo_destilado => new_attributes}, valid_session
        tipo_destilado.reload
        expect(tipo_destilado.nombre).to eq 'nuevo nombre'
      end

      it "assigns the requested tipo_destilado as @tipo_destilado" do
        tipo_destilado = FactoryGirl.create(:tipo_destilado)
        put :update, {:id => tipo_destilado.to_param, :tipo_destilado => valid_attributes}, valid_session
        expect(assigns(:tipo_destilado)).to eq(tipo_destilado)
      end

      it "redirects to the tipo_destilado" do
        tipo_destilado = FactoryGirl.create(:tipo_destilado)
        put :update, {:id => tipo_destilado.to_param, :tipo_destilado => valid_attributes}, valid_session
        expect(response).to redirect_to(tipo_destilado)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_destilado as @tipo_destilado" do
        tipo_destilado = FactoryGirl.create(:tipo_destilado)
        put :update, {:id => tipo_destilado.to_param, :tipo_destilado => invalid_attributes}, valid_session
        expect(assigns(:tipo_destilado)).to eq(tipo_destilado)
      end

      it "re-renders the 'edit' template" do
        tipo_destilado = FactoryGirl.create(:tipo_destilado)
        put :update, {:id => tipo_destilado.to_param, :tipo_destilado => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_destilado" do
      tipo_destilado = FactoryGirl.create(:tipo_destilado)
      expect {
        delete :destroy, {:id => tipo_destilado.to_param}, valid_session
      }.to change(TipoDestilado, :count).by(-1)
    end

    it "redirects to the tipo_destilados list" do
      tipo_destilado = FactoryGirl.create(:tipo_destilado)
      delete :destroy, {:id => tipo_destilado.to_param}, valid_session
      expect(response).to redirect_to(tipo_destilados_url)
    end
  end

end
