require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ZonaProduccionesController, :type => :controller do

  let(:municipio) { FactoryGirl.create :municipio }
  let(:valid_attributes) { { localidad: 'Localidad 1', municipio_id: municipio.id } }

  let(:invalid_attributes) {
    { localidad: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZonaProduccionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:usuario_logueado) { Usuario.new }

  before(:each) { allow_any_instance_of(ApplicationController).to receive(:usuario_actual).and_return usuario_logueado }

  describe "GET index" do
    it "assigns all zona_producciones as @zona_producciones" do
      zona_produccion = FactoryGirl.create(:zona_produccion)
      get :index, {}, valid_session
      expect(assigns(:zona_producciones)).to eq([zona_produccion])
    end
  end

  describe "GET show" do
    it "assigns the requested zona_produccion as @zona_produccion" do
      zona_produccion = FactoryGirl.create(:zona_produccion)
      get :show, {:id => zona_produccion.to_param}, valid_session
      expect(assigns(:zona_produccion)).to eq(zona_produccion)
    end
  end

  describe "GET new" do
    it "assigns a new zona_produccion as @zona_produccion" do
      get :new, {}, valid_session
      expect(assigns(:zona_produccion)).to be_a_new(ZonaProduccion)
    end
  end

  describe "GET edit" do
    it "assigns the requested zona_produccion as @zona_produccion" do
      zona_produccion = FactoryGirl.create(:zona_produccion)
      get :edit, {:id => zona_produccion.to_param}, valid_session
      expect(assigns(:zona_produccion)).to eq(zona_produccion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ZonaProduccion" do
        expect {
          post :create, {:zona_produccion => valid_attributes}, valid_session
        }.to change(ZonaProduccion, :count).by(1)
      end

      it "assigns a newly created zona_produccion as @zona_produccion" do
        post :create, {:zona_produccion => valid_attributes}, valid_session
        expect(assigns(:zona_produccion)).to be_a(ZonaProduccion)
        expect(assigns(:zona_produccion)).to be_persisted
      end

      it "redirects to the created zona_produccion" do
        post :create, {:zona_produccion => valid_attributes}, valid_session
        expect(response).to redirect_to(ZonaProduccion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved zona_produccion as @zona_produccion" do
        post :create, {:zona_produccion => invalid_attributes}, valid_session
        expect(assigns(:zona_produccion)).to be_a_new(ZonaProduccion)
      end

      it "re-renders the 'new' template" do
        post :create, {:zona_produccion => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { localidad: 'nuevo nombre' }
      }

      it "updates the requested zona_produccion" do
        zona_produccion = FactoryGirl.create(:zona_produccion)
        put :update, {:id => zona_produccion.to_param, :zona_produccion => new_attributes}, valid_session
        zona_produccion.reload
        expect(zona_produccion.localidad).to eq 'nuevo nombre'
      end

      it "assigns the requested zona_produccion as @zona_produccion" do
        zona_produccion = FactoryGirl.create(:zona_produccion)
        put :update, {:id => zona_produccion.to_param, :zona_produccion => valid_attributes}, valid_session
        expect(assigns(:zona_produccion)).to eq(zona_produccion)
      end

      it "redirects to the zona_produccion" do
        zona_produccion = FactoryGirl.create(:zona_produccion)
        put :update, {:id => zona_produccion.to_param, :zona_produccion => valid_attributes}, valid_session
        expect(response).to redirect_to(zona_produccion)
      end
    end

    describe "with invalid params" do
      it "assigns the zona_produccion as @zona_produccion" do
        zona_produccion = FactoryGirl.create(:zona_produccion)
        put :update, {:id => zona_produccion.to_param, :zona_produccion => invalid_attributes}, valid_session
        expect(assigns(:zona_produccion)).to eq(zona_produccion)
      end

      it "re-renders the 'edit' template" do
        zona_produccion = FactoryGirl.create(:zona_produccion)
        put :update, {:id => zona_produccion.to_param, :zona_produccion => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested zona_produccion" do
      zona_produccion = FactoryGirl.create(:zona_produccion)
      expect {
        delete :destroy, {:id => zona_produccion.to_param}, valid_session
      }.to change(ZonaProduccion, :count).by(-1)
    end

    it "redirects to the zona_producciones list" do
      zona_produccion = FactoryGirl.create(:zona_produccion)
      delete :destroy, {:id => zona_produccion.to_param}, valid_session
      expect(response).to redirect_to(zona_producciones_url)
    end
  end

end
